TRAIN_INSTANCE_TYPE = 'ml.c5.xlarge'

TRAIN_PERC    = 0.8

EPOCHS        = 10
BATCH_SIZE    = 50
LEARNING_RATE = 1e-4
LATENT_DIM    = 16

TRAIN_ENTRY_POINT       = 'train.py'
TRAIN_SOURCE_DIR        = '../src'

TRAIN_INSTANCE_COUNT    = 1
TRAIN_BASE_JOB_NAME     = 'tf-eager-VAE'
TRAIN_FRAMEWORK_VERSION = '2.3'
TRAIN_PY_VERSION        = 'py37'
TRAIN_SCRIPT_MODE       = True

SAGEMAKER_TFS_DEFAULT_MODEL_NAME = 'vae'

INFERENCE_INITIAL_INSTANCE_COUNT = 1
INFERENCE_INSTANCE_TYPE = 'ml.c5.xlarge'

TRAIN_BUFF = 60000
TEST_BUFF  = 10000